### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [Shaileh/Shabus-Terminal-APP#1]
- לא פתחתם issue
-  דף צוות ריק מתוכן, איפה השונות, מי זה כל אחד מהחברי צוות.
- ניהול סיכונים כללי מדי צריך לפרט יותר, יש במיזם הזה המון סיכונים.

- לוח זמנים, חסר
- אפליקציה בסדר גודל כזה ללא שום תחקיר ובדיקות, לדוגמה רשום 

> Client identifying By Moovit user

האם נבדק שזה אפשרי להתחבר לאפליקציה מוביט? במה זה כרוך?

**Comment by Shaileh** [comment]
- הוספנו תוכן לדף צוות

- הוספנו סיכונים

- הוספנו לוח זמנים

- הוספנו בדיקות ותחקירים בדף וויקי

- אין צורך להתחבר לMOOVIT הם רוצים שהנהג יבדוק בפלאפון של הנוסע אם יש לו את האפליקציה ויוזר והאפלקיציה שלנו רק תאפשר לנהג ללחוץ כן ולא ולעדכן במסד נתונים שהטלפון הזה קיבל נסיעה בגלל MOOVIT

**Comment by YaakovHatam** [comment]
@Shaileh אנא פתחו issue כמו בהוראות

> פתיחת משימה (issue) במאגר הקורס בשם: Check Project 2 Submission ושיוכה למתרגל (הסבר בהמשך - כך תתבצע גם ההגשה במשימות הפרויקט הבאות)
