### ISSUE TITLE
Mission 4 - SDS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [Shaileh/Shabus-Terminal-APP#12]
- יהיה נחמד אם תעשו תוכן עניינים
- הסיכונים של הפרויקט לא רלבנטים, תסתכלו ברשימה שיש לכם ב1.3 ותבנו סיכונים על הפיצ׳רים שיש ברשימה.
- מה עם בדיקות?

**Comment by murradkh** [comment]
ביצענו את השינויים הנדרשים @kob-e
